# -*- coding: utf-8 -*-
"""CIE 1 lab exam

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zaGx1BNCykiZIMu9JUqMOo3_QhpH2qDq
"""

import matplotlib.pyplot as plt
import pandas as pd

df=pd.read_csv('mtcars.csv')
plt.hist(df['mpg'],bins=10,edgecolor='k')
plt.xlabel('mpg')
plt.ylabel('frequency')
plt.title('Histogram')
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

df=pd.read_csv('mtcars.csv')
plt.scatter(df['mpg'],df['wt'])
plt.title('scatter')
plt.xlabel('mpg')
plt.ylabel('frequency')
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

df=pd.read_csv('mtcars.csv')
trans=(df['am'].value_counts())
trans.plot(kind='bar')
plt.xlabel('transimition type')
plt.ylabel('frequency')
plt.title('frequency distribution (bar plot)')
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

df=pd.read_csv('mtcars.csv')
plt.boxplot(df['mpg'])
plt.xlabel('mpg')
plt.ylabel('frequency')
plt.title('boxplot')
plt.show()

import numpy as np
import pandas as pd
Series_a=pd.Series([1,2,3,4,5])
Series_b=pd.Series([2,4,6,8,10])
common=Series_a[Series_a.isin(Series_b)]
df=np.abs(common)
print(df.values)